package com.foobnix.dao2;

import androidx.annotation.Nullable;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Index;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * 文件元数据实体类
 * <p>
 * 映射到数据库表 "FILE_META"，存储书籍文件的所有元数据信息，包括标题、作者、大小、阅读状态等。
 * 使用 greenDAO ORM 框架进行数据持久化。
 */
@Entity
public class FileMeta {

    /** 文件路径（主键，唯一索引） */
    @Id
    @Index(name = "path_desc", unique = true)
    private String path;
    /** 标题（索引） */
    @Index(name = "title_desc")
    private String title;
    /** 作者（索引） */
    @Index(name = "author_desc")
    private String author;
    /** 序列信息 */
    private String sequence;
    /** 分类/类型 */
    private String genre;
    /** 子文件信息 */
    private String child;
    /** 批注/备注 */
    private String annotation;
    /** 排序索引 */
    private Integer sIndex;
    /** 自定义类型 */
    private Integer cusType;
    /** 文件扩展名 */
    private String ext;
    /** 文件大小（字节，索引） */
    @Index(name = "size_desc")
    private Long size;
    /** 修改日期（时间戳，索引） */
    @Index(name = "date_desc")
    private Long date;
    /** 日期文本表示 */
    private String dateTxt;
    /** 大小文本表示 */
    private String sizeTxt;
    /** 路径文本表示（索引） */
    @Index(name = "pathTxt_desc")
    private String pathTxt;
    /** 是否收藏 */
    private Boolean isStar;
    /** 收藏时间 */
    private Long isStarTime;
    /** 是否最近阅读 */
    private Boolean isRecent;
    /** 最近阅读时间 */
    private Long isRecentTime;
    /** 最近阅读进度（0-1） */
    private Float isRecentProgress;
    /** 是否为搜索书籍 */
    private Boolean isSearchBook;
    /** 语言 */
    private String lang;
    /** 标签 */
    private String tag;
    /** 页数 */
    private Integer pages;
    /** 关键字 */
    private String keyword;
    /** 年份 */
    private Integer year;
    /** 状态 */
    private Integer state;
    /** 出版社 */
    private String publisher;
    /** ISBN编号 */
    private String isbn;
    /** 父目录路径（索引） */
    @Index(name = "parentPath_desc")
    private String parentPath;
    /** 文件数量（目录） */
    private Integer filesCount;
    /** 阅读次数 */
    private Integer readCount;

    @Generated
    public FileMeta() {
    }

    public FileMeta(String path) {
        this.path = path;
    }

    @Generated
    public FileMeta(String path, String title, String author, String sequence, String genre, String child, String annotation, Integer sIndex, Integer cusType, String ext, Long size, Long date, String dateTxt, String sizeTxt, String pathTxt, Boolean isStar, Long isStarTime, Boolean isRecent, Long isRecentTime, Float isRecentProgress, Boolean isSearchBook, String lang, String tag, Integer pages, String keyword, Integer year, Integer state, String publisher, String isbn, String parentPath, Integer filesCount, Integer readCount) {
        this.path = path;
        this.title = title;
        this.author = author;
        this.sequence = sequence;
        this.genre = genre;
        this.child = child;
        this.annotation = annotation;
        this.sIndex = sIndex;
        this.cusType = cusType;
        this.ext = ext;
        this.size = size;
        this.date = date;
        this.dateTxt = dateTxt;
        this.sizeTxt = sizeTxt;
        this.pathTxt = pathTxt;
        this.isStar = isStar;
        this.isStarTime = isStarTime;
        this.isRecent = isRecent;
        this.isRecentTime = isRecentTime;
        this.isRecentProgress = isRecentProgress;
        this.isSearchBook = isSearchBook;
        this.lang = lang;
        this.tag = tag;
        this.pages = pages;
        this.keyword = keyword;
        this.year = year;
        this.state = state;
        this.publisher = publisher;
        this.isbn = isbn;
        this.parentPath = parentPath;
        this.filesCount = filesCount;
        this.readCount = readCount;
    }

    @Override
    public boolean equals(@Nullable Object obj) {
        return obj != null && path.equals(((FileMeta) obj).path);
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getSequence() {
        return sequence;
    }

    public void setSequence(String sequence) {
        this.sequence = sequence;
    }

    public String getGenre() {
        return genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    public String getChild() {
        return child;
    }

    public void setChild(String child) {
        this.child = child;
    }

    public String getAnnotation() {
        return annotation;
    }

    public void setAnnotation(String annotation) {
        this.annotation = annotation;
    }

    public Integer getSIndex() {
        return sIndex;
    }

    public void setSIndex(Integer sIndex) {
        this.sIndex = sIndex;
    }

    public Integer getCusType() {
        return cusType;
    }

    public void setCusType(Integer cusType) {
        this.cusType = cusType;
    }

    public String getExt() {
        return ext;
    }

    public void setExt(String ext) {
        this.ext = ext;
    }

    public Long getSize() {
        return size;
    }

    public void setSize(Long size) {
        this.size = size;
    }

    public Long getDate() {
        return date;
    }

    public void setDate(Long date) {
        this.date = date;
    }

    public String getDateTxt() {
        return dateTxt;
    }

    public void setDateTxt(String dateTxt) {
        this.dateTxt = dateTxt;
    }

    public String getSizeTxt() {
        return sizeTxt;
    }

    public void setSizeTxt(String sizeTxt) {
        this.sizeTxt = sizeTxt;
    }

    public String getPathTxt() {
        return pathTxt;
    }

    public void setPathTxt(String pathTxt) {
        this.pathTxt = pathTxt;
    }

    public Boolean getIsStar() {
        return isStar;
    }

    public void setIsStar(Boolean isStar) {
        this.isStar = isStar;
    }

    public Long getIsStarTime() {
        return isStarTime;
    }

    public void setIsStarTime(Long isStarTime) {
        this.isStarTime = isStarTime;
    }

    public Boolean getIsRecent() {
        return isRecent;
    }

    public void setIsRecent(Boolean isRecent) {
        this.isRecent = isRecent;
    }

    public Long getIsRecentTime() {
        return isRecentTime;
    }

    public void setIsRecentTime(Long isRecentTime) {
        this.isRecentTime = isRecentTime;
    }

    public Float getIsRecentProgress() {
        return isRecentProgress;
    }

    public void setIsRecentProgress(Float isRecentProgress) {
        this.isRecentProgress = isRecentProgress;
    }

    public Boolean getIsSearchBook() {
        return isSearchBook;
    }

    public void setIsSearchBook(Boolean isSearchBook) {
        this.isSearchBook = isSearchBook;
    }

    public String getLang() {
        return lang;
    }

    public void setLang(String lang) {
        this.lang = lang;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public Integer getPages() {
        return pages;
    }

    public void setPages(Integer pages) {
        this.pages = pages;
    }

    public String getKeyword() {
        return keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public Integer getYear() {
        return year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public String getPublisher() {
        return publisher;
    }

    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    public String getIsbn() {
        return isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    public String getParentPath() {
        return parentPath;
    }

    public void setParentPath(String parentPath) {
        this.parentPath = parentPath;
    }

    public Integer getFilesCount() {
        return filesCount;
    }

    public void setFilesCount(Integer filesCount) {
        this.filesCount = filesCount;
    }

    public Integer getReadCount() {
        return readCount;
    }

    public void setReadCount(Integer readCount) {
        this.readCount = readCount;
    }

}
